<?php

namespace Database\Seeders;

use App\Models\Billboard;
use Illuminate\Database\Seeder;

class BillboardSeeder extends Seeder
{
    public function run(): void
    {
        $billboards = [
            [
                'title' => 'Gulshan-2 Circle Unipole',
                'address' => 'Gulshan Circle 2, Gulshan, Dhaka',
                'latitude' => 23.7925,
                'longitude' => 90.4078,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 180000,
                'rating' => 4.6,
                'status' => 'available',
            ],
            [
                'title' => 'Gulshan-1 DCC Market Billboard',
                'address' => 'Gulshan 1 DCC Market, Gulshan, Dhaka',
                'latitude' => 23.7805,
                'longitude' => 90.4152,
                'size' => '30ft x 15ft',
                'type' => 'multipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 220000,
                'rating' => 4.3,
                'status' => 'available',
            ],
            [
                'title' => 'Banani 11 Road LED Screen',
                'address' => 'Road 11, Banani, Dhaka',
                'latitude' => 23.7967,
                'longitude' => 90.4034,
                'size' => '15ft x 25ft',
                'type' => 'led',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 260000,
                'rating' => 4.8,
                'status' => 'available',
            ],
            [
                'title' => 'Banani Rail Crossing Unipole',
                'address' => 'Banani Rail Crossing, Banani, Dhaka',
                'latitude' => 23.7937,
                'longitude' => 90.4066,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'daily',
                'daily_rate' => 6500,
                'monthly_rate' => null,
                'rating' => 4.1,
                'status' => 'available',
            ],
            [
                'title' => 'Dhanmondi 27 Wall Wrap',
                'address' => 'Road 27, Dhanmondi, Dhaka',
                'latitude' => 23.7461,
                'longitude' => 90.3742,
                'size' => '25ft x 12ft',
                'type' => 'wall',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 90000,
                'rating' => 3.9,
                'status' => 'booked',
            ],
            [
                'title' => 'Dhanmondi 32 Neon Sign',
                'address' => 'Road 32, Dhanmondi, Dhaka',
                'latitude' => 23.7508,
                'longitude' => 90.3762,
                'size' => '10ft x 8ft',
                'type' => 'neon',
                'pricing_mode' => 'daily',
                'daily_rate' => 3000,
                'monthly_rate' => null,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Motijheel Shapla Chattar Billboard',
                'address' => 'Shapla Chattar, Motijheel, Dhaka',
                'latitude' => 23.7275,
                'longitude' => 90.4145,
                'size' => '40ft x 20ft',
                'type' => 'multipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 300000,
                'rating' => 4.7,
                'status' => 'available',
            ],
            [
                'title' => 'Motijheel Commercial Area Unipole',
                'address' => 'Dilkusha C/A, Motijheel, Dhaka',
                'latitude' => 23.7330,
                'longitude' => 90.4172,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 150000,
                'rating' => 4.2,
                'status' => 'available',
            ],
            [
                'title' => 'Mirpur-10 Circle LED',
                'address' => 'Mirpur 10 Circle, Mirpur, Dhaka',
                'latitude' => 23.8069,
                'longitude' => 90.3687,
                'size' => '15ft x 25ft',
                'type' => 'led',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 200000,
                'rating' => 4.4,
                'status' => 'available',
            ],
            [
                'title' => 'Mirpur-1 Bus Stand Billboard',
                'address' => 'Mirpur 1 Bus Stand, Mirpur, Dhaka',
                'latitude' => 23.7965,
                'longitude' => 90.3536,
                'size' => '20ft x 10ft',
                'type' => 'freestanding',
                'pricing_mode' => 'daily',
                'daily_rate' => 4500,
                'monthly_rate' => null,
                'rating' => 3.8,
                'status' => 'available',
            ],
            [
                'title' => 'Uttara Sector-7 Unipole',
                'address' => 'Sector 7, Uttara, Dhaka',
                'latitude' => 23.8759,
                'longitude' => 90.3795,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 130000,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Uttara House Building Rd Billboard',
                'address' => 'House Building Road, Uttara, Dhaka',
                'latitude' => 23.8698,
                'longitude' => 90.3958,
                'size' => '30ft x 15ft',
                'type' => 'static',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 170000,
                'rating' => 4.3,
                'status' => 'available',
            ],
            [
                'title' => 'Mohakhali Bus Terminal Wall',
                'address' => 'Mohakhali Bus Terminal, Mohakhali, Dhaka',
                'latitude' => 23.7790,
                'longitude' => 90.4057,
                'size' => '25ft x 12ft',
                'type' => 'wall',
                'pricing_mode' => 'daily',
                'daily_rate' => 5000,
                'monthly_rate' => null,
                'rating' => 3.7,
                'status' => 'available',
            ],
            [
                'title' => 'Mohakhali DOHS Gate Unipole',
                'address' => 'DOHS Gate, Mohakhali, Dhaka',
                'latitude' => 23.7896,
                'longitude' => 90.4017,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 140000,
                'rating' => 4.1,
                'status' => 'available',
            ],
            [
                'title' => 'Farmgate Overbridge Billboard',
                'address' => 'Farmgate Overbridge, Farmgate, Dhaka',
                'latitude' => 23.7565,
                'longitude' => 90.3897,
                'size' => '30ft x 15ft',
                'type' => 'gantry',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 210000,
                'rating' => 4.5,
                'status' => 'available',
            ],
            [
                'title' => 'Kawran Bazar LED Tower',
                'address' => 'Kawran Bazar, Dhaka',
                'latitude' => 23.7508,
                'longitude' => 90.3928,
                'size' => '15ft x 25ft',
                'type' => 'led',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 280000,
                'rating' => 4.7,
                'status' => 'available',
            ],
            [
                'title' => 'Panthapath Signal Unipole',
                'address' => 'Panthapath Signal, Dhaka',
                'latitude' => 23.7503,
                'longitude' => 90.3862,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'daily',
                'daily_rate' => 5500,
                'monthly_rate' => null,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Shahbagh Circle Billboard',
                'address' => 'Shahbagh Circle, Dhaka',
                'latitude' => 23.7381,
                'longitude' => 90.3954,
                'size' => '20ft x 10ft',
                'type' => 'freestanding',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 160000,
                'rating' => 3.9,
                'status' => 'booked',
            ],
            [
                'title' => 'Malibagh Chowdhurypara Unipole',
                'address' => 'Malibagh Chowdhurypara, Dhaka',
                'latitude' => 23.7501,
                'longitude' => 90.4166,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'daily',
                'daily_rate' => 4000,
                'monthly_rate' => null,
                'rating' => 3.6,
                'status' => 'available',
            ],
            [
                'title' => 'Rampura Bridge Wall Wrap',
                'address' => 'Rampura Bridge, Dhaka',
                'latitude' => 23.7583,
                'longitude' => 90.4250,
                'size' => '25ft x 12ft',
                'type' => 'wall',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 80000,
                'rating' => 3.8,
                'status' => 'available',
            ],
            [
                'title' => 'Badda Link Road Billboard',
                'address' => 'Badda Link Road, Dhaka',
                'latitude' => 23.7808,
                'longitude' => 90.4265,
                'size' => '20ft x 10ft',
                'type' => 'static',
                'pricing_mode' => 'daily',
                'daily_rate' => 3800,
                'monthly_rate' => null,
                'rating' => 3.5,
                'status' => 'available',
            ],
            [
                'title' => 'Bashundhara Gate Unipole',
                'address' => 'Bashundhara Gate, Baridhara, Dhaka',
                'latitude' => 23.8145,
                'longitude' => 90.4351,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 190000,
                'rating' => 4.4,
                'status' => 'available',
            ],
            [
                'title' => 'Jatrabari Flyover Billboard',
                'address' => 'Jatrabari Flyover, Dhaka',
                'latitude' => 23.7104,
                'longitude' => 90.4335,
                'size' => '30ft x 15ft',
                'type' => 'gantry',
                'pricing_mode' => 'daily',
                'daily_rate' => 4200,
                'monthly_rate' => null,
                'rating' => 3.4,
                'status' => 'booked',
            ],
            [
                'title' => 'Mohammadpur Bus Stand Unipole',
                'address' => 'Mohammadpur Bus Stand, Dhaka',
                'latitude' => 23.7656,
                'longitude' => 90.3589,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 110000,
                'rating' => 3.9,
                'status' => 'available',
            ],
            [
                'title' => 'Shyamoli Square Neon Sign',
                'address' => 'Shyamoli Square, Dhaka',
                'latitude' => 23.7699,
                'longitude' => 90.3654,
                'size' => '10ft x 8ft',
                'type' => 'neon',
                'pricing_mode' => 'daily',
                'daily_rate' => 2800,
                'monthly_rate' => null,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Tejgaon Industrial Area Wall',
                'address' => 'Tejgaon I/A, Dhaka',
                'latitude' => 23.7699,
                'longitude' => 90.3985,
                'size' => '25ft x 12ft',
                'type' => 'wall',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 70000,
                'rating' => 3.7,
                'status' => 'available',
            ],
            [
                'title' => 'Elephant Road Shopping Belt LED',
                'address' => 'Elephant Road, Dhaka',
                'latitude' => 23.7398,
                'longitude' => 90.3833,
                'size' => '15ft x 25ft',
                'type' => 'led',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 240000,
                'rating' => 4.6,
                'status' => 'available',
            ],
            [
                'title' => 'Baridhara Diplomatic Zone Billboard',
                'address' => 'Baridhara DOHS, Dhaka',
                'latitude' => 23.8079,
                'longitude' => 90.4193,
                'size' => '30ft x 15ft',
                'type' => 'backlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 250000,
                'rating' => 4.5,
                'status' => 'booked',
            ],
            [
                'title' => 'Uttara Sector-4 Unipole',
                'address' => 'Sector 4, Uttara, Dhaka',
                'latitude' => 23.8795,
                'longitude' => 90.3910,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 125000,
                'rating' => 3.9,
                'status' => 'available',
            ],
            [
                'title' => 'Bashundhara R/A Main Gate LED',
                'address' => 'Main Gate, Bashundhara R/A, Dhaka',
                'latitude' => 23.8213,
                'longitude' => 90.4275,
                'size' => '15ft x 25ft',
                'type' => 'led',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 270000,
                'rating' => 4.6,
                'status' => 'available',
            ],
            [
                'title' => 'Khilgaon Circle Unipole',
                'address' => 'Khilgaon Circle, Dhaka',
                'latitude' => 23.7472,
                'longitude' => 90.4293,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'daily',
                'daily_rate' => 4300,
                'monthly_rate' => null,
                'rating' => 3.7,
                'status' => 'available',
            ],
            [
                'title' => 'Segunbagicha Wall Wrap',
                'address' => 'Segunbagicha, Dhaka',
                'latitude' => 23.7346,
                'longitude' => 90.4088,
                'size' => '25ft x 12ft',
                'type' => 'wall',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 85000,
                'rating' => 3.6,
                'status' => 'available',
            ],
            [
                'title' => 'New Market Billboard',
                'address' => 'New Market, Dhaka',
                'latitude' => 23.7328,
                'longitude' => 90.3855,
                'size' => '30ft x 15ft',
                'type' => 'rooftop',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 195000,
                'rating' => 4.2,
                'status' => 'available',
            ],
            [
                'title' => 'Azimpur Circle Unipole',
                'address' => 'Azimpur Circle, Dhaka',
                'latitude' => 23.7280,
                'longitude' => 90.3830,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'daily',
                'daily_rate' => 3900,
                'monthly_rate' => null,
                'rating' => 3.5,
                'status' => 'available',
            ],
            [
                'title' => 'Kalabagan Bus Stand Neon Sign',
                'address' => 'Kalabagan Bus Stand, Dhaka',
                'latitude' => 23.7457,
                'longitude' => 90.3831,
                'size' => '10ft x 8ft',
                'type' => 'neon',
                'pricing_mode' => 'daily',
                'daily_rate' => 2600,
                'monthly_rate' => null,
                'rating' => 3.8,
                'status' => 'available',
            ],
            [
                'title' => 'Moghbazar Wireless Gate Billboard',
                'address' => 'Wireless Gate, Moghbazar, Dhaka',
                'latitude' => 23.7495,
                'longitude' => 90.4085,
                'size' => '30ft x 15ft',
                'type' => 'gantry',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 175000,
                'rating' => 4.1,
                'status' => 'available',
            ],
            [
                'title' => 'Shantinagar Signal Unipole',
                'address' => 'Shantinagar Signal, Dhaka',
                'latitude' => 23.7365,
                'longitude' => 90.4157,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'daily',
                'daily_rate' => 4600,
                'monthly_rate' => null,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Gulistan Zero Point LED',
                'address' => 'Zero Point, Gulistan, Dhaka',
                'latitude' => 23.7275,
                'longitude' => 90.4110,
                'size' => '15ft x 25ft',
                'type' => 'led',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 290000,
                'rating' => 4.5,
                'status' => 'available',
            ],
            [
                'title' => 'Sayedabad Bus Terminal Wall',
                'address' => 'Sayedabad Bus Terminal, Dhaka',
                'latitude' => 23.7217,
                'longitude' => 90.4341,
                'size' => '25ft x 12ft',
                'type' => 'wall',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 75000,
                'rating' => 3.6,
                'status' => 'available',
            ],
            [
                'title' => 'Khilkhet Rail Gate Unipole',
                'address' => 'Rail Gate, Khilkhet, Dhaka',
                'latitude' => 23.8285,
                'longitude' => 90.4256,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 115000,
                'rating' => 3.8,
                'status' => 'available',
            ],
            [
                'title' => 'Nikunja-2 Gate Billboard',
                'address' => 'Nikunja-2 Gate, Dhaka',
                'latitude' => 23.8235,
                'longitude' => 90.4098,
                'size' => '30ft x 15ft',
                'type' => 'gantry',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 165000,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Kuril Bishwa Road LED',
                'address' => 'Bishwa Road, Kuril, Dhaka',
                'latitude' => 23.8228,
                'longitude' => 90.4180,
                'size' => '15ft x 25ft',
                'type' => 'led',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 255000,
                'rating' => 4.4,
                'status' => 'available',
            ],
            [
                'title' => 'Gabtoli Bus Terminal Wall',
                'address' => 'Gabtoli Bus Terminal, Dhaka',
                'latitude' => 23.7802,
                'longitude' => 90.3439,
                'size' => '25ft x 12ft',
                'type' => 'wall',
                'pricing_mode' => 'daily',
                'daily_rate' => 3600,
                'monthly_rate' => null,
                'rating' => 3.4,
                'status' => 'available',
            ],
            [
                'title' => 'Chawkbazar Old Dhaka Unipole',
                'address' => 'Chawkbazar, Old Dhaka',
                'latitude' => 23.7186,
                'longitude' => 90.3925,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'daily',
                'daily_rate' => 3200,
                'monthly_rate' => null,
                'rating' => 3.5,
                'status' => 'available',
            ],
            [
                'title' => 'Wari Rankin Street Billboard',
                'address' => 'Rankin Street, Wari, Dhaka',
                'latitude' => 23.7175,
                'longitude' => 90.4224,
                'size' => '20ft x 10ft',
                'type' => 'frontlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 105000,
                'rating' => 3.7,
                'status' => 'available',
            ],
            [
                'title' => 'Lalbagh Fort Road Neon Sign',
                'address' => 'Fort Road, Lalbagh, Dhaka',
                'latitude' => 23.7188,
                'longitude' => 90.3887,
                'size' => '10ft x 8ft',
                'type' => 'neon',
                'pricing_mode' => 'daily',
                'daily_rate' => 2400,
                'monthly_rate' => null,
                'rating' => 3.6,
                'status' => 'available',
            ],
            [
                'title' => 'Paltan Circle Unipole',
                'address' => 'Paltan Circle, Dhaka',
                'latitude' => 23.7331,
                'longitude' => 90.4128,
                'size' => '20ft x 10ft',
                'type' => 'unipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 145000,
                'rating' => 4.1,
                'status' => 'available',
            ],
            [
                'title' => 'Kurmitola Airport Road LED',
                'address' => 'Airport Road, Kurmitola, Dhaka',
                'latitude' => 23.8437,
                'longitude' => 90.4034,
                'size' => '15ft x 25ft',
                'type' => 'led',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 265000,
                'rating' => 4.5,
                'status' => 'available',
            ],
            [
                'title' => 'Uttara Sector-10 Overpass Rooftop',
                'address' => 'Sector 10, Uttara, Dhaka',
                'latitude' => 23.8689,
                'longitude' => 90.3814,
                'size' => '25ft x 15ft',
                'type' => 'rooftop',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 160000,
                'rating' => 4.2,
                'status' => 'available',
            ],
            [
                'title' => 'Uttara Sector-3 Flyover Gantry',
                'address' => 'Sector 3, Uttara, Dhaka',
                'latitude' => 23.8668,
                'longitude' => 90.3925,
                'size' => '30ft x 12ft',
                'type' => 'gantry',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 195000,
                'rating' => 4.4,
                'status' => 'available',
            ],
            [
                'title' => 'Uttara Diabari Bus Stand LED',
                'address' => 'Diabari, Uttara, Dhaka',
                'latitude' => 23.8825,
                'longitude' => 90.3705,
                'size' => '15ft x 25ft',
                'type' => 'led',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 235000,
                'rating' => 4.5,
                'status' => 'available',
            ],
            [
                'title' => 'Uttara Abdullahpur Neon Sign',
                'address' => 'Abdullahpur, Uttara, Dhaka',
                'latitude' => 23.8823,
                'longitude' => 90.4014,
                'size' => '10ft x 8ft',
                'type' => 'neon',
                'pricing_mode' => 'daily',
                'daily_rate' => 3200,
                'monthly_rate' => null,
                'rating' => 3.9,
                'status' => 'available',
            ],
            [
                'title' => 'Uttara Rajlakshmi Complex Multipole',
                'address' => 'Rajlakshmi Complex, Sector 7, Uttara, Dhaka',
                'latitude' => 23.8742,
                'longitude' => 90.3839,
                'size' => '20ft x 12ft',
                'type' => 'multipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 205000,
                'rating' => 4.3,
                'status' => 'available',
            ],
            [
                'title' => 'Uttara Jasimuddin Circle Freestanding',
                'address' => 'Jasimuddin, Sector 3, Uttara, Dhaka',
                'latitude' => 23.8712,
                'longitude' => 90.3982,
                'size' => '20ft x 10ft',
                'type' => 'freestanding',
                'pricing_mode' => 'daily',
                'daily_rate' => 4800,
                'monthly_rate' => null,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Uttara Sector-13 Wall Wrap',
                'address' => 'Sector 13, Uttara, Dhaka',
                'latitude' => 23.8621,
                'longitude' => 90.3899,
                'size' => '25ft x 12ft',
                'type' => 'wall',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 78000,
                'rating' => 3.7,
                'status' => 'available',
            ],
            [
                'title' => 'Uttara President Road Backlit Sign',
                'address' => 'President Road, Sector 11, Uttara, Dhaka',
                'latitude' => 23.8776,
                'longitude' => 90.3901,
                'size' => '20ft x 10ft',
                'type' => 'backlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 188000,
                'rating' => 4.1,
                'status' => 'available',
            ],
            [
                'title' => 'Uttara BNS Center Frontlit Panel',
                'address' => 'BNS Center, Sector 7, Uttara, Dhaka',
                'latitude' => 23.8757,
                'longitude' => 90.3822,
                'size' => '18ft x 10ft',
                'type' => 'frontlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 172000,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Mohammadpur Town Hall Static Panel',
                'address' => 'Town Hall Road, Mohammadpur, Dhaka',
                'latitude' => 23.7628,
                'longitude' => 90.3600,
                'size' => '20ft x 10ft',
                'type' => 'static',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 95000,
                'rating' => 3.8,
                'status' => 'available',
            ],
            [
                'title' => 'Adabor Ring Road Static Sign',
                'address' => 'Ring Road, Adabor, Dhaka',
                'latitude' => 23.7715,
                'longitude' => 90.3568,
                'size' => '20ft x 10ft',
                'type' => 'static',
                'pricing_mode' => 'daily',
                'daily_rate' => 3400,
                'monthly_rate' => null,
                'rating' => 3.6,
                'status' => 'available',
            ],
            [
                'title' => 'Shyamoli Ring Road Static Board',
                'address' => 'Ring Road, Shyamoli, Dhaka',
                'latitude' => 23.7745,
                'longitude' => 90.3660,
                'size' => '20ft x 10ft',
                'type' => 'static',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 88000,
                'rating' => 3.7,
                'status' => 'available',
            ],
            [
                'title' => 'Kallyanpur Bus Stand Static Panel',
                'address' => 'Kallyanpur Bus Stand, Dhaka',
                'latitude' => 23.7723,
                'longitude' => 90.3612,
                'size' => '20ft x 10ft',
                'type' => 'static',
                'pricing_mode' => 'daily',
                'daily_rate' => 3600,
                'monthly_rate' => null,
                'rating' => 3.5,
                'status' => 'available',
            ],
            [
                'title' => 'Mirpur-2 Zoo Road Static Sign',
                'address' => 'Zoo Road, Mirpur 2, Dhaka',
                'latitude' => 23.8130,
                'longitude' => 90.3540,
                'size' => '20ft x 10ft',
                'type' => 'static',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 92000,
                'rating' => 3.9,
                'status' => 'available',
            ],
            [
                'title' => 'Mirpur-6 Section Static Board',
                'address' => 'Section 6, Mirpur, Dhaka',
                'latitude' => 23.8050,
                'longitude' => 90.3600,
                'size' => '20ft x 10ft',
                'type' => 'static',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 90000,
                'rating' => 3.7,
                'status' => 'available',
            ],
            [
                'title' => 'Mirpur-11 Pallabi Backlit Sign',
                'address' => 'Pallabi, Mirpur 11, Dhaka',
                'latitude' => 23.8214,
                'longitude' => 90.3690,
                'size' => '20ft x 10ft',
                'type' => 'backlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 190000,
                'rating' => 4.2,
                'status' => 'available',
            ],
            [
                'title' => 'Mirpur-12 Kalshi Backlit Panel',
                'address' => 'Kalshi, Mirpur 12, Dhaka',
                'latitude' => 23.8380,
                'longitude' => 90.3690,
                'size' => '20ft x 10ft',
                'type' => 'backlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 205000,
                'rating' => 4.3,
                'status' => 'available',
            ],
            [
                'title' => 'Mirpur-14 Signboard Backlit Display',
                'address' => 'Signboard, Mirpur 14, Dhaka',
                'latitude' => 23.8000,
                'longitude' => 90.3720,
                'size' => '20ft x 10ft',
                'type' => 'backlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 198000,
                'rating' => 4.1,
                'status' => 'available',
            ],
            [
                'title' => 'Agargaon IDB Bhaban Backlit Sign',
                'address' => 'IDB Bhaban, Agargaon, Dhaka',
                'latitude' => 23.7783,
                'longitude' => 90.3796,
                'size' => '20ft x 10ft',
                'type' => 'backlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 215000,
                'rating' => 4.4,
                'status' => 'available',
            ],
            [
                'title' => 'Sher-e-Bangla Nagar Backlit Panel',
                'address' => 'Sher-e-Bangla Nagar, Dhaka',
                'latitude' => 23.7676,
                'longitude' => 90.3768,
                'size' => '20ft x 10ft',
                'type' => 'backlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 208000,
                'rating' => 4.2,
                'status' => 'available',
            ],
            [
                'title' => 'Green Road Backlit Display',
                'address' => 'Green Road, Dhaka',
                'latitude' => 23.7495,
                'longitude' => 90.3768,
                'size' => '20ft x 10ft',
                'type' => 'backlit',
                'pricing_mode' => 'daily',
                'daily_rate' => 6200,
                'monthly_rate' => null,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Panthapath Square Frontlit Panel',
                'address' => 'Panthapath Square, Dhaka',
                'latitude' => 23.7520,
                'longitude' => 90.3860,
                'size' => '18ft x 10ft',
                'type' => 'frontlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 175000,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Kawran Bazar TCB Bhaban Frontlit Sign',
                'address' => 'TCB Bhaban, Kawran Bazar, Dhaka',
                'latitude' => 23.7517,
                'longitude' => 90.3927,
                'size' => '18ft x 10ft',
                'type' => 'frontlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 182000,
                'rating' => 4.1,
                'status' => 'available',
            ],
            [
                'title' => 'Eskaton Garden Frontlit Board',
                'address' => 'Eskaton Garden Road, Dhaka',
                'latitude' => 23.7420,
                'longitude' => 90.4055,
                'size' => '18ft x 10ft',
                'type' => 'frontlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 168000,
                'rating' => 3.9,
                'status' => 'available',
            ],
            [
                'title' => 'Kakrail Mosque Road Frontlit Panel',
                'address' => 'Mosque Road, Kakrail, Dhaka',
                'latitude' => 23.7345,
                'longitude' => 90.4113,
                'size' => '18ft x 10ft',
                'type' => 'frontlit',
                'pricing_mode' => 'daily',
                'daily_rate' => 5600,
                'monthly_rate' => null,
                'rating' => 3.8,
                'status' => 'available',
            ],
            [
                'title' => 'Dilkusha C/A Tower Frontlit Display',
                'address' => 'Dilkusha C/A, Dhaka',
                'latitude' => 23.7267,
                'longitude' => 90.4180,
                'size' => '18ft x 10ft',
                'type' => 'frontlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 190000,
                'rating' => 4.3,
                'status' => 'available',
            ],
            [
                'title' => 'Gendaria Bridge Frontlit Sign',
                'address' => 'Gendaria Bridge, Dhaka',
                'latitude' => 23.7091,
                'longitude' => 90.4210,
                'size' => '18ft x 10ft',
                'type' => 'frontlit',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 160000,
                'rating' => 3.7,
                'status' => 'available',
            ],
            [
                'title' => 'Sutrapur Circle Multipole',
                'address' => 'Sutrapur Circle, Dhaka',
                'latitude' => 23.7104,
                'longitude' => 90.4177,
                'size' => '20ft x 12ft',
                'type' => 'multipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 210000,
                'rating' => 4.2,
                'status' => 'available',
            ],
            [
                'title' => 'Postogola Bridge Multipole',
                'address' => 'Postogola Bridge, Dhaka',
                'latitude' => 23.6989,
                'longitude' => 90.4245,
                'size' => '20ft x 12ft',
                'type' => 'multipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 225000,
                'rating' => 4.4,
                'status' => 'available',
            ],
            [
                'title' => 'Demra Staff Quarter Multipole',
                'address' => 'Staff Quarter, Demra, Dhaka',
                'latitude' => 23.7186,
                'longitude' => 90.4450,
                'size' => '20ft x 12ft',
                'type' => 'multipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 195000,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Kadamtali Bus Stand Multipole',
                'address' => 'Kadamtali Bus Stand, Dhaka',
                'latitude' => 23.7043,
                'longitude' => 90.4390,
                'size' => '20ft x 12ft',
                'type' => 'multipole',
                'pricing_mode' => 'daily',
                'daily_rate' => 6800,
                'monthly_rate' => null,
                'rating' => 3.9,
                'status' => 'available',
            ],
            [
                'title' => 'Keraniganj Bridge Approach Multipole',
                'address' => 'Bridge Approach, Keraniganj, Dhaka',
                'latitude' => 23.7062,
                'longitude' => 90.3961,
                'size' => '20ft x 12ft',
                'type' => 'multipole',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 200000,
                'rating' => 4.1,
                'status' => 'available',
            ],
            [
                'title' => 'Bosila Bridge Freestanding Board',
                'address' => 'Bosila Bridge, Dhaka',
                'latitude' => 23.7480,
                'longitude' => 90.3390,
                'size' => '20ft x 10ft',
                'type' => 'freestanding',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 145000,
                'rating' => 3.9,
                'status' => 'available',
            ],
            [
                'title' => 'Adabor Shekertek Freestanding Sign',
                'address' => 'Shekertek, Adabor, Dhaka',
                'latitude' => 23.7645,
                'longitude' => 90.3535,
                'size' => '20ft x 10ft',
                'type' => 'freestanding',
                'pricing_mode' => 'daily',
                'daily_rate' => 4700,
                'monthly_rate' => null,
                'rating' => 3.7,
                'status' => 'available',
            ],
            [
                'title' => 'Rayerbazar Freestanding Panel',
                'address' => 'Rayerbazar, Dhaka',
                'latitude' => 23.7460,
                'longitude' => 90.3620,
                'size' => '20ft x 10ft',
                'type' => 'freestanding',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 138000,
                'rating' => 3.8,
                'status' => 'available',
            ],
            [
                'title' => 'Zigatola Freestanding Board',
                'address' => 'Zigatola, Dhaka',
                'latitude' => 23.7385,
                'longitude' => 90.3745,
                'size' => '20ft x 10ft',
                'type' => 'freestanding',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 150000,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Hazaribagh Freestanding Sign',
                'address' => 'Hazaribagh, Dhaka',
                'latitude' => 23.7280,
                'longitude' => 90.3670,
                'size' => '20ft x 10ft',
                'type' => 'freestanding',
                'pricing_mode' => 'daily',
                'daily_rate' => 4300,
                'monthly_rate' => null,
                'rating' => 3.6,
                'status' => 'available',
            ],
            [
                'title' => 'Lalmatia Gantry Overpass',
                'address' => 'Lalmatia, Dhaka',
                'latitude' => 23.7530,
                'longitude' => 90.3690,
                'size' => '30ft x 12ft',
                'type' => 'gantry',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 205000,
                'rating' => 4.3,
                'status' => 'available',
            ],
            [
                'title' => 'Kalabagan Lake Circus Gantry',
                'address' => 'Lake Circus, Kalabagan, Dhaka',
                'latitude' => 23.7480,
                'longitude' => 90.3820,
                'size' => '30ft x 12ft',
                'type' => 'gantry',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 198000,
                'rating' => 4.2,
                'status' => 'available',
            ],
            [
                'title' => 'Nilkhet Book Market Gantry',
                'address' => 'Nilkhet, Dhaka',
                'latitude' => 23.7330,
                'longitude' => 90.3860,
                'size' => '30ft x 12ft',
                'type' => 'gantry',
                'pricing_mode' => 'daily',
                'daily_rate' => 6300,
                'monthly_rate' => null,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Palashi Crossing Gantry',
                'address' => 'Palashi Crossing, Dhaka',
                'latitude' => 23.7275,
                'longitude' => 90.3900,
                'size' => '30ft x 12ft',
                'type' => 'gantry',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 188000,
                'rating' => 4.1,
                'status' => 'available',
            ],
            [
                'title' => 'Bakshibazar Rooftop Display',
                'address' => 'Bakshibazar, Dhaka',
                'latitude' => 23.7245,
                'longitude' => 90.3940,
                'size' => '25ft x 15ft',
                'type' => 'rooftop',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 165000,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Ramna Park Gate Rooftop Sign',
                'address' => 'Ramna Park Gate, Dhaka',
                'latitude' => 23.7365,
                'longitude' => 90.4020,
                'size' => '25ft x 15ft',
                'type' => 'rooftop',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 178000,
                'rating' => 4.2,
                'status' => 'available',
            ],
            [
                'title' => 'Fakirapool Rooftop Panel',
                'address' => 'Fakirapool, Dhaka',
                'latitude' => 23.7330,
                'longitude' => 90.4160,
                'size' => '25ft x 15ft',
                'type' => 'rooftop',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 158000,
                'rating' => 3.9,
                'status' => 'available',
            ],
            [
                'title' => 'Arambagh Rooftop Board',
                'address' => 'Arambagh, Dhaka',
                'latitude' => 23.7300,
                'longitude' => 90.4185,
                'size' => '25ft x 15ft',
                'type' => 'rooftop',
                'pricing_mode' => 'daily',
                'daily_rate' => 5400,
                'monthly_rate' => null,
                'rating' => 3.8,
                'status' => 'available',
            ],
            [
                'title' => 'Purana Paltan Neon Sign',
                'address' => 'Purana Paltan, Dhaka',
                'latitude' => 23.7340,
                'longitude' => 90.4130,
                'size' => '10ft x 8ft',
                'type' => 'neon',
                'pricing_mode' => 'daily',
                'daily_rate' => 2900,
                'monthly_rate' => null,
                'rating' => 3.9,
                'status' => 'available',
            ],
            [
                'title' => 'Bijoynagar Neon Display',
                'address' => 'Bijoynagar, Dhaka',
                'latitude' => 23.7360,
                'longitude' => 90.4145,
                'size' => '10ft x 8ft',
                'type' => 'neon',
                'pricing_mode' => 'daily',
                'daily_rate' => 3100,
                'monthly_rate' => null,
                'rating' => 4.0,
                'status' => 'available',
            ],
            [
                'title' => 'Malibagh Rail Gate Neon Sign',
                'address' => 'Rail Gate, Malibagh, Dhaka',
                'latitude' => 23.7495,
                'longitude' => 90.4200,
                'size' => '10ft x 8ft',
                'type' => 'neon',
                'pricing_mode' => 'daily',
                'daily_rate' => 2700,
                'monthly_rate' => null,
                'rating' => 3.7,
                'status' => 'available',
            ],
            [
                'title' => 'Khilgaon Taltola LED Screen',
                'address' => 'Taltola, Khilgaon, Dhaka',
                'latitude' => 23.7440,
                'longitude' => 90.4270,
                'size' => '15ft x 25ft',
                'type' => 'led',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 245000,
                'rating' => 4.4,
                'status' => 'available',
            ],
            [
                'title' => 'Basabo LED Tower',
                'address' => 'Basabo, Dhaka',
                'latitude' => 23.7370,
                'longitude' => 90.4285,
                'size' => '15ft x 25ft',
                'type' => 'led',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 230000,
                'rating' => 4.3,
                'status' => 'available',
            ],
                        [
                'title' => 'Kamarpara Billboard',
                'address' => 'Kamarpara, Dhaka',
                'latitude' => 23.8916,
                'longitude' => 90.3882,
                'size' => '15ft x 25ft',
                'type' => 'Static',
                'pricing_mode' => 'monthly',
                'daily_rate' => 0,
                'monthly_rate' => 130000,
                'rating' => 4.3,
                'status' => 'available',
            ],
        ];

        foreach ($billboards as $billboard) {
            Billboard::create($billboard);
        }
    }
}
